# Generated by Django 4.2.4 on 2023-08-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0002_showroom_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
