# Generated by Django 4.2.4 on 2023-08-10 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0003_showroom_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showroom",
            name="email",
        ),
    ]
