# Generated by Django 4.2.4 on 2023-08-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0004_remove_showroom_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
