# Generated by Django 4.2.4 on 2023-08-10 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0006_alter_showroom_created_by_car"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
