# Generated by Django 4.2.4 on 2023-08-11 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0009_alter_car_created_by_showroomdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomdetails",
            name="show_room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_room_details",
                to="car.showroom",
            ),
        ),
    ]
