# Generated by Django 4.2.4 on 2023-08-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0011_alter_car_show_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="show_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showroom_all_cars",
                to="car.showroom",
            ),
        ),
    ]
