# Generated by Django 4.2.4 on 2023-08-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a1", "0002_alter_book_author_alter_review_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=100)),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="author_all_songs", to="a1.author"
                    ),
                ),
            ],
        ),
    ]
