# Generated by Django 4.2.4 on 2023-08-10 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoassign",
            old_name="assigned_by_user_id",
            new_name="assigned_by_user_idd",
        ),
    ]
