# Generated by Django 4.2.4 on 2023-08-10 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_rename_assigned_by_user_id_todoassign_assigned_by_user_idd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoassign",
            old_name="assigned_by_user_idd",
            new_name="assigned_by_user_id",
        ),
    ]
