# Generated by Django 4.2.4 on 2023-08-14 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a2", "0002_rename_postuser_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Task",
        ),
    ]
