# Generated by Django 4.2.4 on 2023-08-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a2", "0003_rename_posts_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(related_name="tasks_assigned", to="a2.user"),
        ),
    ]
