# Generated by Django 4.2.4 on 2023-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a2", "0005_course_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(to="a2.student"),
        ),
    ]
