# Generated by Django 4.2.4 on 2023-08-14 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a2", "0006_course_students"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
