# Generated by Django 4.2.4 on 2023-08-14 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a2", "0008_course_student_enrollment_course_students"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
