# Generated by Django 4.2.4 on 2023-08-14 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a2", "0009_alter_enrollment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
    ]
