# Generated by Django 4.2.4 on 2023-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_author_profile_url_authorprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_url",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
