# Generated by Django 4.2.4 on 2023-08-11 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_alter_author_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorprofile",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="AuthorProfile",
        ),
    ]
