# Generated by Django 4.2.4 on 2023-08-12 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0013_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
