# Generated by Django 4.2.4 on 2023-08-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0017_subject_unit_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_units",
                to="book.subject",
            ),
        ),
    ]
