# Generated by Django 4.2.4 on 2023-08-13 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0018_alter_unit_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="subject",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
