# Generated by Django 4.2.4 on 2023-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetail",
            name="price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
