# Generated by Django 4.2.4 on 2023-08-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_alter_invoicedetail_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetail",
            name="invoice_number",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_detail",
                to="invoice.invoice",
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "invoice_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_invoice_detail",
                        to="invoice.invoice",
                    ),
                ),
            ],
        ),
    ]
