# Generated by Django 4.2.4 on 2023-08-14 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_alter_invoicedetail_invoice_number_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
