# Generated by Django 4.2.4 on 2023-08-14 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0008_alter_invoicedetail_invoice_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoicedetail",
            old_name="invoice_number",
            new_name="invoice",
        ),
    ]
